package harness

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// OpenCode is the adapter for the OpenCode harness.
// OpenCode uses JS/TS plugin files in .opencode/plugins/ for hooks,
// not JSON config entries.
type OpenCode struct{}

func (o *OpenCode) Name() string { return "opencode" }

func (o *OpenCode) Detect(dir string) bool {
	info, err := os.Stat(filepath.Join(dir, ".opencode"))
	if err == nil && info.IsDir() {
		return true
	}
	_, err = os.Stat(filepath.Join(dir, "opencode.json"))
	return err == nil
}

func (o *OpenCode) SettingsPath() string {
	return filepath.Join(".opencode", "plugins", "union-hooks.mjs")
}

func (o *OpenCode) Capabilities() []string {
	return []string{
		"SessionStart",
		"PreToolUse",
		"PostToolUse",
		"UserPrompt",
		"Stop",
		"PreCommit",
	}
}

func (o *OpenCode) Supports(event string) bool {
	for _, e := range o.Capabilities() {
		if e == event {
			return true
		}
	}
	return false
}

func openCodeEventName(event string) string {
	switch event {
	case "SessionStart":
		return "session.created"
	case "PreToolUse":
		return "tool.execute.before"
	case "PostToolUse":
		return "tool.execute.after"
	case "UserPrompt":
		return "message.updated"
	case "Stop":
		return "session.deleted"
	case "PreCommit":
		return "tool.before.bash"
	default:
		return event
	}
}

func normalizeOpenCodeEvent(event string) string {
	switch event {
	case "session.created":
		return "SessionStart"
	case "tool.execute.before":
		return "PreToolUse"
	case "tool.execute.after":
		return "PostToolUse"
	case "message.updated":
		return "UserPrompt"
	case "session.deleted":
		return "Stop"
	case "tool.before.bash":
		return "PreCommit"
	default:
		return event
	}
}

var pluginTmpl = template.Must(template.New("plugin").Parse(`// Generated by union — do not edit manually.
// Re-generate with: union emit --write
import { execSync } from "child_process";

export const UnionHooks = async ({ client, project, $, directory }) => {
  return {
{{- range .Hooks }}
    "{{ .Event }}": async (input, output) => {
      try {
        execSync({{ .CommandJSON }}, {
          cwd: directory,
          stdio: "pipe",
          {{- if .Timeout }}
          timeout: {{ .Timeout }},
          {{- end }}
        });
      } catch (e) {
        {{- if eq .Degrade "error" }}
        throw e;
        {{- else if eq .Degrade "warn" }}
        console.warn("[union] hook failed:", e.message);
        {{- end }}
      }
    },
{{- end }}
  };
};
`))

type pluginHook struct {
	Event       string
	CommandJSON string
	Timeout     int
	Degrade     string
}

func (o *OpenCode) Emit(hooks []Hook, existing []byte) ([]byte, error) {
	var phooks []pluginHook
	for _, h := range hooks {
		if !o.Supports(h.Event) {
			continue
		}
		phooks = append(phooks, pluginHook{
			Event:       openCodeEventName(h.Event),
			CommandJSON: jsString(unionManagedPrefix + h.Command),
			Timeout:     h.Timeout,
			Degrade:     h.Degrade,
		})
	}

	if len(phooks) == 0 {
		return []byte("// Generated by union — no hooks configured.\nexport const UnionHooks = async () => ({});\n"), nil
	}

	var buf strings.Builder
	if err := pluginTmpl.Execute(&buf, struct{ Hooks []pluginHook }{phooks}); err != nil {
		return nil, fmt.Errorf("render opencode plugin: %w", err)
	}
	return []byte(buf.String()), nil
}

func (o *OpenCode) Import(config []byte) ([]Hook, error) {
	// Parse existing plugin file by scanning for execSync calls with
	// event name context. Best-effort — plugin files are JS, not structured.
	content := string(config)
	lines := strings.Split(content, "\n")

	var hooks []Hook
	var currentEvent string
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Match event handler: "session.created": async ...
		if strings.Contains(trimmed, `": async`) {
			parts := strings.SplitN(trimmed, `"`, 3)
			if len(parts) >= 3 {
				evt := parts[1]
				norm := normalizeOpenCodeEvent(evt)
				if norm != evt {
					currentEvent = norm
				}
			}
		}

		// Match execSync call to extract command.
		if currentEvent != "" && strings.Contains(trimmed, "execSync(") {
			cmd := extractJSString(trimmed)
			if cmd != "" {
				hooks = append(hooks, Hook{
					Event:   currentEvent,
					Command: cmd,
					Degrade: "skip",
				})
				currentEvent = ""
			}
		}
	}
	return hooks, nil
}

// jsString returns a JSON-safe JS string literal.
func jsString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	return `"` + s + `"`
}

// extractJSString pulls the first quoted string argument from an execSync call.
func extractJSString(line string) string {
	idx := strings.Index(line, "execSync(")
	if idx < 0 {
		return ""
	}
	rest := line[idx+len("execSync("):]
	if len(rest) == 0 || rest[0] != '"' {
		return ""
	}
	rest = rest[1:]
	end := strings.Index(rest, `"`)
	if end < 0 {
		return ""
	}
	return rest[:end]
}

// PluginFingerprint returns a short hash of hook content for cache-busting.
func PluginFingerprint(hooks []Hook) string {
	h := sha256.New()
	for _, hook := range hooks {
		fmt.Fprintf(h, "%s:%s:%s\n", hook.Event, hook.Matcher, hook.Command)
	}
	sum := fmt.Sprintf("%x", h.Sum(nil))
	if len(sum) > 8 {
		return sum[:8]
	}
	return sum
}
